allow_anonymous true

# Log general information (connections, subscribes, publishes, etc.)
log_type information

# Show warnings and errors too
log_type warning
log_type error

# Output logs to terminal
log_dest stdout

listener 1884